Upgrade to node 22
Error: Node.js Version "18.x" is discontinued and must be upgraded. Please set Node.js Version to 22.x in your Project Settings to use Node.js 22.
Learn More: http://vercel.link/node-version